- package-lock.json
- package.json
- src/Buttons/ToolbarIconButton.tsx
- src/DraftEditor.tsx
- src/DraftToolbar/BoldFormat.tsx
- src/DraftToolbar/DraftBackgroundColor.tsx
- src/DraftToolbar/DraftFontColor.tsx
- src/DraftToolbar/DraftToolbar.tsx
- src/DraftToolbar/FontFamilyFormat.tsx
- src/DraftToolbar/FontSizeFormat.tsx
- src/DraftToolbar/ItalicFormat.tsx
- src/Styles/DraftEditor.less
- src/Styles/ToolbarSelect.less
- src/Styles/index.ts
- webpack.config.js
- Updated the UI for editor Format bar
- Fixed state update issue on Format bar
@nsdevaraj
> Editor Format bar UI changes

- PULL_REQUEST_TEMPLATE.md
- src/DraftToolbar/DraftBackgroundColor.tsx
- src/DraftToolbar/DraftFontColor.tsx
- src/Styles/ToolbarSelect.less
- Color picker UI changes in editor toolbar
@nsdevaraj
> Color picker UI changes in editor toolbar

- src/DraftEditor.tsx
> adding fullname into mentionList

- package.json
- src/DraftEditor.tsx
> updating custom color code for mentions 

- package.json
- src/DraftEditor.tsx
- src/Styles/MentionStyle.css
> searching mention user, donot call onChange

- package.json
> package.json script update

- package.json
- src/Service/draftEditor.ts
> fix(editor): Line Height and Local build fix

- src/DraftEditor.tsx
1.  [x] Editor
Added placeholder props to editor
@nsdevaraj
> Added placeholder props to editor

- src/DraftEditor.tsx
1.  [x] Editor
feat: Added insert text at cursor feature
@nsdevaraj
> feat: Added insert text at cursor feature

- package-lock.json
- src/DraftEditor.tsx
- src/Service/UIconstants.ts
- src/Service/draftEditor.ts
1.  [x] Editor
Feat(Alignment):Text alignment option added
@nsdevaraj
> Feat(Alignment):Text alignment option added

- src/DraftEditor.tsx
- src/Mention.tsx
- src/Styles/Mention.less
- src/Styles/MentionStyle.css
- src/Styles/MentionStyle.less
> dark theme fixes

- src/DraftEditor.tsx
> Key binding added for submit

- src/DraftEditor.tsx
1.  [x] Editor
Formatter resetting on focus fix
@nsdevaraj
> Formatter resetting on focus fix

- src/DraftEditor.tsx
1.  [x] Editor
Value suggestion limit increased to 15
@nsdevaraj
> Value suggestion limit increased to 15

- src/DraftEditor.tsx
1.  [x] Editor
Restrict formatting to apply without selection
@nsdevaraj
> fix(editor): Restrict formatting to apply without selection

- src/DraftEditor.tsx
> Reset editor state added.

- src/DraftEditor.tsx
> Mentions breaking issue fix

- src/DraftEditor.tsx
> editor auto-focus added

- src/DraftEditor.tsx
> fix(mentions): editor focus causes mentions to stop working fix

- src/Components/PopOverContainer.tsx
> fix(mentions): rendering outside client window issue fixed

- src/DraftEditor.tsx
1.  [X] Editor
-   [X] NEW FEATURE IMPLEMENTATION
> added funtion to mover cursor at end

- package-lock.json
- package.json
- src/Components/PopOverContainer.tsx
- src/DraftEditor.tsx
> fix(mentions): reply edit breaking mentions fix

- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
1.  [x] Editor
When emptying the editor sometimes an empty tag can also be used like `<p></p>` so added code to support that.
@nsdevaraj
> fix(editor): Fixed empy editor state

- package-lock.json
- package.json
- src/DraftEditor.tsx
1.  [x] Editor
Added support to copy-paste entity between the editors
@nsdevaraj
> feat(editor): Added support to copy paste entity between the editors

- package.json
- src/DraftEditor.tsx
> insertTextAtCursor with textcolor

- package.json
- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
1.  [x] Editor
Entity breaking on the change made so reverting it
@nsdevaraj
> fix(editor): Entity not working fix

- src/DraftEditor.tsx
> custom link support added in toolbarComponent props

- src/DraftEditor.tsx
> revert commit

- src/Service/UIconstants.ts
@jeffersonswartz Please review.
> Added text strikethrough toolbar feature for drafr editor.

- src/Service/draftEditor.service.tsx
@jeffersonswartz Please review.
> Don't merge: handled html conversion for text for strike through toolbar option.

- src/DraftEditor.tsx
1.  [x] Editor
Added selection props to show format toolbar on text selection in charts
@nsdevaraj
> Added selection props to show format toolbar on text selection in charts

- src/App.tsx
> updated local test component

- src/DraftEditor.tsx
> blur editor when mention is triggered

- src/DraftEditor.tsx
> text color added when adding insertTextAtcursor

- src/DraftEditor.tsx
- src/Service/UIconstants.ts
- src/Service/draftEditor.service.tsx
1.  [x] Editor
Added text align option
@nsdevaraj
> Added text align option

- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
1.  [x] Editor
Changed text alignment flow
@nsdevaraj
> Changed text alignment flow

- src/DraftEditor.tsx
> escape event added for submit

- src/Service/draftEditor.service.tsx
1.  [x] Editor
Added underline option in draft editor
@nsdevaraj
> Added underline option in draft editor

- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
> fix(annotation): hash mention fixed

- src/Service/draftEditor.service.tsx
> set background color as transparent

- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
1.  [ ] Editor
2.  [x] Toolbar
> strikeThrough enable/disable button issue fixed

- src/DraftEditor.tsx
> decorator plugin added in constructor

- src/Service/draftEditor.service.tsx
> remove color from convertToHtml in service

- src/Components/ValueMentionSuggestionList.tsx
- src/DraftEditor.tsx
- src/Styles/Mention.less
> new Mention UX

- src/Components/PopOverContainer.tsx
- src/Components/ValueMentionSuggestionList.tsx
- src/DraftEditor.tsx
- src/Styles/Mention.less
> feat(annotation): custom mention implementation completed

- src/DraftEditor.tsx
1.  [x] Editor
Added option to replace selection when insert entity or text
@nsdevaraj
> feat(editor): Added option to replace selection when insert entity or text

- src/DraftEditor.tsx
> ValueMentionProps list issue fixed

- src/Components/ValueMentionSuggestionList.tsx
- src/DraftEditor.tsx
> Incomplete mention change color to red

- package-lock.json
- package.json
- src/Components/ValueMentionSuggestionList.tsx
- src/DraftEditor.tsx
> people mention scroill issue fixed

- gulpfile.js
- package-lock.json
- package.json
- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
- src/Styles/InlineToolbar.less
- src/Styles/index.ts
- chore: added dev npm script
- feat: added support for inline toolbar and link
1.  [x] Editor
> feat: added support for inline toolbar and link

- src/DraftEditor.tsx
> fix(draft): Mentions and styles getting removed fix

- src/Components/SuggestionList.tsx
- src/Styles/Mention.less
> VBI-4750 fixed

- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
> unique data-id added to mentions

- src/Components/PopOverContainer.tsx
- src/DraftEditor.tsx
- src/Styles/Mention.less
> XPC-6900 fixed

- src/Components/PopOverContainer.tsx
> mention dropdown bounding issue fixed

- src/DraftEditor.tsx
- src/Service/draftEditor.service.tsx
> Formula in data value mention 

- src/DraftEditor.tsx
> fix(link): VBI-4951 last character gets left out

- src/Service/draftEditor.service.tsx
> fix(Charts): PBX-12748 Console error issue fixed

- src/Components/ValueMentionSuggestionList.tsx
> value data mention, ellipses css update

- src/DraftEditor.tsx
1.  [x] Editor
Changes upon review
@manikandanvengatesan @nsdevaraj
> fix(charts): code review changes -update

- package-lock.json
- package.json
- src/Components/SuggestionList.tsx
- src/Components/ValueMentionSuggestionList.tsx
- src/DraftEditor.tsx
> @lumel/mention added and XPC-8057 fixed

- package-lock.json
- package.json
> merged with main branch

- src/DraftEditor.tsx
> fix(mention): mention triggers with # and . fixed

- src/DraftEditor.tsx
- src/Service/UIconstants.ts
> feat(draftjs): orderedlist, unorderedlist and checklist toolbar option added

- src/DraftEditor.tsx
> initial change re-render condition added

- src/DraftEditor.tsx
> revert conditional render for prop change

- src/Service/draftEditor.service.tsx
> with formula donot update mention key

- src/Service/draftEditor.service.tsx
> fontsize added to DraftElementFormat

- src/Components/SuggestionList.tsx
> fix(mention): tooltip added to peopleMention

- src/DraftApi.ts
> feat(draft-api): added truncate api

- src/DraftApi.ts
> fix(draft-api): added getFormattedValue back

- src/Components/PopOverContainer.tsx
- src/DraftEditor.tsx
> XPC-10577 mention drop down misaligned with smaller visual size

- src/DraftEditor.tsx
> minor props condition fix

- src/DraftEditor.tsx
> fix(mention): XPC-10577 fixed

- src/DraftEditor.tsx
1.  [ ] Editor
2.  [x] Toolbar
> select utility added in toolbar props

- src/App.tsx
1.  [ ] Editor
As discussed with @jeffersonswartz, commented  code used for dev purposes for certification
@jeffersonswartz @nsdevaraj @vbiarulkumar
> chore(App): commented dev code

- package-lock.json
- src/DraftEditor.tsx
> feat(charts-mention): merged # and @ mention in kpi and formula

- src/DraftEditor.tsx
1.  [ ] Editor
2.  [x] Toolbar
> feat(selection): added hasSelection prop

- src/Service/draftEditor.service.tsx
1.  [x] Editor
@nsdevaraj @Raghu3130 @jeffersonswartz @manikandanvengatesan
> moveColorToTop removed as it causing issue in fontformat

- src/DraftEditor.tsx
> feat(selection): added hasSelection prop for in place toolbar

- src/Components/SuggestionList.tsx
- src/Styles/Mention.less
> fix: mention user in comments initial changes

- src/DraftApi.ts
> fix(Text Column Formatting): Formatting not working in Measures in Rows VBI-5575

- src/DraftEditor.tsx
1.  [ ] Editor
___
enhancement
___
- Added an optional `onTab` function prop to the `IDraftEditorProps` interface.
- Updated the `onTab` method in the `DraftEditor` class to call the `onTab` prop if it is provided.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>DraftEditor.tsx</strong><dd><code>Add optional `onTab` function prop to `DraftEditor`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/DraftEditor.tsx
<li>Added <code>onTab</code> prop to <code>IDraftEditorProps</code> interface.<br> <li> Modified …
> chore(tab): add optional on tab function

- src/Components/SuggestionList.tsx
- src/Components/ValueMentionSuggestionList.tsx
- src/DraftEditor.tsx
1.  [X] Editor
-   [X] BUG FIX
fix(mention): fixed arrow navigation for mention
@nsdevaraj , @jeffersonswartz
___
Bug fix, Enhancement
___
- Implemented arrow navigation for mentions in the `DraftEditor` component by introducing a new prop `mentionArrowNavigation`.
- Enhanced styling for mention items in `SuggestionList` and `ValueMentionSuggestionList` components by adding an active state class.
- Adjusted key binding logic to accommodate the new arrow navigation feature.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …
> fix(mention): fixed arrow navigation for mention
